IMAC/IMAC/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), #Path Buat admin
    path('home/', include('mainweb.urls')), #Path buat aplikasi IMAC
    path('', RedirectView.as_view(url='home/', permanent=True)), #Path klo ada org nulis langsung alamat site nde browser
    path('accounts/', include('django.contrib.auth.urls')), #Path account, deprecated, account semua lewat home sekarang
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) #Path buat static (css, gambar dll)

handler404 = "mainweb.views.handle_not_found"

IMAC/mainweb/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('error', views.error, name='error'),
    path('login',views.user_login, name='customlogin'),
    path('recruitment2023',views.admitted, name='admitted'),
    path('signup',views.register, name='customsignup'),
    path('find-your-manager', views.your_manajer, name = 'yourmanajer')
]

IMAC/mainweb/models.py
from django.db import models
from datetime import datetime
from datetime import date
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone
from .utils import custom_id

#Jangan lupa register model ke admin site yaa

class UserManager(BaseUserManager):

  def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
    if not email:
        raise ValueError('Users must have an email address')
    now = timezone.now()
    email = self.normalize_email(email)
    user = self.model(
        email=email,
        is_staff=is_staff, 
        is_active=True,
        is_superuser=is_superuser, 
        last_login=datetime.now(),
        date_joined=date.today(), 
        **extra_fields
    )
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_user(self, email, password, **extra_fields):
    return self._create_user(email, password, False, False, **extra_fields)

  def create_superuser(self, email, password, **extra_fields):
    user=self._create_user(email, password, True, True, **extra_fields)
    return user

class User(AbstractBaseUser, PermissionsMixin):
    custom_id = models.CharField(primary_key=True, max_length=11, unique=True, default=custom_id)
    email = models.EmailField(max_length=254, unique=True)
    nrp = models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')], null=True, blank=True, verbose_name='NRP')
    IMACid =models.CharField(max_length=5, validators=[RegexValidator(r'^\d{1,5}$')]) 
    name = models.CharField(max_length=254, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(null=True, blank=True)
    
    GROUP_CHOICE = (
        ('s', 'Staff'),
        ('m', 'Manager'),
        ('x', 'Member'),
        ('g', 'Guest'),
    )
    
    usergroup = models.CharField(
        max_length=1,
        choices=GROUP_CHOICE,
        blank=True,
        default='g',
        help_text='User Type')
    

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

class Instansi(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    INSTANSI_CHOICE = (
        ('i', 'ITS'),
        ('o', 'Non-ITS'),
    )
    JURUSAN_CHOICE = (
        ('oo', 'Non-ITS'),
        ('f', 'Fisika'),
        ('k', 'Kimia'),
        ('m', 'Matematika'),
        ('s', 'Statistika'),
        ('a', 'Aktuaria'),
        ('b', 'Biologi'),
        ('sa', 'Sains Analitik dan Instrumentasi Kimia'),
        ('tm', 'Teknik Mesin'),
        ('tk', 'Teknik Kimia'),
        ('tf', 'Teknik Fisika'),
        ('ti', 'Teknik Sistem dan Industri'),
        ('tm', 'Teknik Material'),
        ('tp', 'Teknik Pangan'),
        ('ts', 'Teknik Sipil'),
        ('ar', 'Arsitektur'),
        ('tl', 'Teknik Lingkungan'),
        ('pw', 'Perencanaan Wilayah dan Kota'),
        ('gm', 'Teknik Geomatika'),
        ('gf', 'Teknik Geofisika'),
        ('tp', 'Teknik Perkapalan'),
        ('sk', 'Teknik Sistem Perkapalan'),
        ('kl', 'Teknik Kelautan'),
        ('la', 'Teknik Transportasi Laut'),
        ('lp', 'Teknik Lepas Pantai'),
        ('ee', 'Teknik Elektro'),
        ('eb', 'Teknik Biomedik'),
        ('ec', 'Teknik Komputer'),
        ('et', 'Teknik Telekomunikasi'),
        ('et', 'Teknologi Kedokteran'),
        ('ei', 'Informatika'),
        ('es', 'Sistem Informasi'),
        ('ex', 'Teknologi Informasi'),
        ('dp', 'Desain Produk'),
        ('di', 'Desain Interior'),
        ('dk', 'Desain Komunikasi Visual'),
        ('mb', 'Manajemen Bisnis'),
        ('sp','Studi Pembangunan'),
        ('4e', 'Teknik Elektro Otomasi'),
        ('4i', 'Teknik Instrumentasi'),
        ('4s', 'Teknik Infrastruktur Sipil'),
        ('4m', 'Teknik Mesin Industri'),
        ('4k', 'Teknik Kimia Industri'),
        ('4s', 'Statistika Bisnis'),
    )

    instansi = models.CharField(
        max_length=1,
        choices=INSTANSI_CHOICE,
        blank=True,
        default='i',
        help_text='Asal Instansi')
    jurusan = models.CharField(max_length=2,
        choices=JURUSAN_CHOICE,
        blank=True,
        default='oo',
        help_text='Asal Jurusan')

class IMACevents(models.Model):
    title = models.CharField(max_length=20, help_text='Masukkan nama event' )
    startregistdate = models.DateField()
    startdate = models.DateTimeField()
    enddate = models.DateTimeField()
    attendee = models.ManyToManyField(User)
    agenda = models.CharField(max_length=1000, help_text='Deskripsi singkat event')

    class Meta:
         verbose_name = "IMAC Event"

class article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    contributor = models.OneToOneField(User,on_delete=models.RESTRICT, default='Anonymous')
    releasedate = models.DateField()

    class Meta:
         verbose_name = "IMAC Article"

#Nama manajer masih ga user friendly di tampilan adminnya, fix soon
class Nama_Manajer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    manajer = models.CharField(max_length=5, null=True, blank=True)

class Divisi(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    DIVISI_CHOICE = (
        ('IR', 'Metallurgy'),
        ('SD', 'Material'),
        ('ER','Mineral'),
        ('RP','Mining'),
        ('WD', 'Extractive'),
        ('CR','Coal'),
        ('MD','Manufacture'),
        ('CC','Excavator'),
        ('FU','Pyrometallurgy'),
        ('SP', 'Blast Furnace'),
    )
    divisi = models.CharField(max_length=2,
        choices=DIVISI_CHOICE,
        blank=True,
        default='oo',
        help_text='Asal Divisi')

IMAC/mainweb/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import User

#Kalo bikin form bikin disini yaaa
class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        print (str(email))
        print (str(password))
        if not user or not user.is_active:
            print('form validation error')
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data

    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    name = forms.CharField()

    class Meta:
        model = User
        fields = ['name','email','password1','password2']
        field_order = ['email','name','password1','password2']

    def clean(self):
#Verifies that the values entered into the password fields match Note : errors here will appear in 'non_field_errors()
        cleaned_data = super(RegistrationForm, self).clean()
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError("Passwords don't match. Please try again!")
        return self.cleaned_data

    def save(self, commit=True):
        user = super(RegistrationForm,self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
#The save(commit=False) tells Django to save the new record, but dont commit it to the database yet

IMAC/mainweb/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages
from .forms import LoginForm, RegistrationForm
from .models import IMACevents, article, User, Nama_Manajer, Divisi
from django.http import HttpResponseRedirect,JsonResponse
from datetime import datetime
from django.views import View
import io,csv
from django.template import RequestContext

#Page Login
def user_login(request):
    form = LoginForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            user = form.login(request)
            if user:
                login(request, user)
                return redirect('yourmanajer')# Redirect to a success page.
        else:
            messages.error(request,'Email or Password do not match')
            form = LoginForm()
    else:
        form = LoginForm()
    context = {'form': form,}

    return render(request, 'registration/login.html', context)

#Page Registration (Belum ada templatenya)
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(data = request.POST)
        if form.is_valid():
            user = form.save()
            email = user.email
            password = user.password
            u = authenticate(email = email, password = password)
            login(request,u)
            return redirect('home')
    else:
        form = RegistrationForm()

    return render(request,'registration/register.html',{'form':form,})

#Homepage (Tapi belum dipake, nanti bisa dipake buat nampilin event terbaru)
"""
def home(request):
    num_member = User.objects.all().count()
    num_events = IMACevents.objects.all().count()
    num_article = article.objects.all().count()

    context = {
        'num_member' : num_member,
        'num_events' : num_events,
        'num_article' : num_article,
    }

    return render(request, 'home.html', context=context)
"""

#Page error dedicated
def error(request):
    return render(request, 'error.html')

#Page home sekarang(Static)
def home(request):
	return render(request,'home.html')

#Page pengumuman/admitted, nanti diganti page user profile 
@login_required
def admitted(request):
    current_user = request.user
    if current_user.usergroup == 'x':
        nama = current_user.name
        jurusan = current_user.jurusan
        nrp = current_user.nrp
        id_imac = current_user.IMACid
        context = {
                    'nama' : nama,
                    'jurusan' : jurusan,
                    'nrp' : nrp,
                    'id_imac' : id_imac,
                }
        return render(request,'admitted.html', context=context)
    else:
        pass
    return render(request,'rejected.html')

#Page handler error 404 sama 500
def handler404(request, *args, **argv):
    context = RequestContext(request)
    response = render(None, 'error.html', context=context)
                                  
    response.status_code = 404
    return response


def handler500(request, *args, **argv):
    response = render('error.html', {},
                                  context_instance=RequestContext(request))
    response.status_code = 500
    return response #Gatau bisa ato ngga

def handle_not_found(request, exception):
    return render(request, "error.html")

#Page buat nyari query manajer, jadiin view ini buat contoh narik data dari db 
def your_manajer(request):
    my_manager = Nama_Manajer.objects.filter(user=request.user)[0]
    my_divisi = Divisi.objects.filter(user=request.user)
    nama_manager =my_manager.manajer
    nama_divisi = my_divisi
    context = {
        'nama_manager': nama_manager,
        'nama_divisi': nama_divisi,
    }
    return render(request,'nama_manajer.html', context=context)


 

IMAC/mainweb/templates/admitted.html
{% extends "base_generic.html" %}

{% block content %}
<div class="flex max-w-screen justify-center items-center p-4">
    <div class ="flex flex-col items-center backdrop-blur pt-12 pb-8 rounded-3xl w-9/12 lg:w-8/12 px-6 mx-6 h-full bg-no-repeat bg-origin-content backdrop-opacity-100 bg-contain bg-right-bottom" style="background-image: url(/static/bego_imac_generic.png)">
        <div class="mb-6 flex flex-row overflow-y-visible w-full h-4 lg:h-8">
            <div class="flex flex-col flex-1 bg-orange-500 justify-end items-center">
                <div>
                <h1 class="text-center text-3xl lg:text-6xl text-white font-black drop-shadow-[0_3px_5px_rgba(10,10,10,15)]">Congratulations !</h1>
                </div>
            </div>
        </div>
        <div class="mb-6 flex flex-col lg:flex-row px-8 justify-center items-center w-full">
            <div class="flex-none">
                <h5 class="w-24 md:w-32 text-center whitespace-nowrap block mx-2 p-0.5 lg:p-2 bg-orange-500 rounded-lg text-sm font-medium text-white ">Name</h5>
            </div>
            <div class="flex w-full flex-col flex-1 bg-gray-50 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 p-0.5 lg:p-2">
                <div>
                    <h5 class="text-gray-900 text-center text-sm font-medium">{{ nama }}</h5>
                </div>
            </div>
        </div>
        <div class="mb-6 flex flex-col lg:flex-row px-8 justify-center items-center w-full">
            <div class="flex-none">
                <h5 class="w-24 md:w-32 text-center whitespace-nowrap block mx-2 p-0.5 lg:p-2 bg-orange-500 rounded-lg text-sm font-medium text-white ">Major</h5>
            </div>
            <div class="flex w-full flex-col flex-1 bg-gray-50 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 p-0.5 lg:p-2">
                <div>
                    <h5 class="text-gray-900 text-center text-sm font-medium">{{ jurusan }}</h5>
                </div>
            </div>
        </div>
        <div class="mb-6 flex flex-col lg:flex-row px-8 justify-center items-center w-full">
            <div class="flex-none">
                <h5 class="w-24 md:w-32 text-center whitespace-nowrap block mx-2 p-0.5 lg:p-2 bg-orange-500 rounded-lg text-sm font-medium text-white ">NRP</h5>
            </div>
            <div class="flex w-full flex-col flex-1 bg-gray-50 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 p-0.5 lg:p-2">
                <div>
                    <h5 class="text-gray-900 text-center text-sm font-medium">{{ nrp }}</h5>
                </div>
            </div>
        </div>
        <div class="mb-6 flex flex-col lg:flex-row px-8 justify-center items-center w-full">
            <div class="flex-none">
                <h5 class="w-24 md:w-32 text-center whitespace-nowrap block mx-2 p-0.5 lg:p-2 bg-orange-500 rounded-lg text-sm font-medium text-white ">ID IMAC</h5>
            </div>
            <div class="flex w-full flex-col flex-1 bg-gray-50 border border-gray-300 rounded-lg focus:ring-red-500 focus:border-red-500 p-0.5 lg:p-2">
                <div>
                    <h5 class="text-gray-900 text-center text-sm font-medium">{{ id_imac }}</h5>
                </div>
            </div>
        </div>
        <p class = "mx-8 leading-normal text-center text-md text-gray-100">All of your hardwork is paid off!! We're looking forward for your contribution in IMAC :)</p>
        <p class = "mx-8 text-center leading-normal text-md text-gray-100">P.S. Don't forget to join the welcome party</p>
    </div>
</div>
{% endblock content %}

IMAC/mainweb/templates/base_generic.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IMAC</title>
    <link rel="icon" type="image/x-icon" href="/static/logo_imac.png">

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body class="bg-cover bg-scroll" style = "background-image:url('/static/bg-home.jpg')">
    <!--Navbar-->
    <nav class="bg-transparent backdrop-blur border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
        <div class="container flex flex-wrap items-center justify-between mx-auto">
          <a href="{{ .Site.Params.homepage }}/" class="flex items-center">
              <img src="/static/logo_its.png" class="h-6 mr-3 sm:h-12" alt="ITS Logo" />
              <img src="/static/logo_imac.png" class="h-6 mr-3 sm:h-12" alt="IMAC Logo" />
          </a>
          <button data-collapse-toggle="mobile-menu" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-neutral-600 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
            <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          </button>
          <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
            <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
              <li>
                <a href="{% url 'home' %}" class="block py-2 pl-3 pr-4 text-gray-100 underline bg-green-700 rounded md:bg-transparent md:text-gray-100 md:p-0 dark:text-white" aria-current="page">Home</a>
              </li>
              <li>
                <a href="{%  url 'customlogin' %}" class="block py-2 pl-3 pr-4 text-gray-100 underline border-b border-gray-100 hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Login</a>
              </li>
              <li>
                <a href="#" class="block py-2 pl-3 pr-4 text-gray-100 border-b underline border-gray-100  hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Our Team</a>
              </li>
              <li>
                <a href="#" class="block py-2 pl-3 pr-4 text-gray-100 border-b underline border-gray-100 hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Events</a>
              </li>
              <li>
                <a href="#" class="block py-2 pl-3 pr-4 text-gray-100 underline hover:bg-transparent md:border-0 md:hover:text-green-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Article</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!--Navbar end-->
    <div class="container mx-auto mt-4">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://unpkg.com/flowbite@1.6.0/dist/flowbite.min.js"></script>
</body>

</html>

IMAC/mainweb/templates/nama_manajer.html
{% extends "base_generic.html" %}
{% block content %}
<div class="flex flex-col items-center">
    <div class=" flex max-h-screen">
    <div class="flex flex-col self-center items-center py-4 px-6 m-10 items-center bg-transparent backdrop-blur rounded-3xl xl:mx-48" >
        <div>    
            <h1 class="text-[#dad2c9] text-5xl text-center font-bold leading-none underline underline-offset-8 decoration-3 lg:decoration-2 decoration-orange-600 md:text-7xl lg:text-8xl drop-shadow-[0_5px_5px_rgba(0,0,0,5)]">{{ nama_manager }}</h1>
            {% for x in nama_divisi %}
            <h3 class="text-[#dad2c9] text-2xl text-center font-bold leading-none lg:text-3xl drop-shadow-[0_5px_5px_rgba(0,0,0,5)]">{{ x.get_divisi_display }}</h3>
            {% endfor %}
            <div class="text-lg text-center font-semibold text-white leading-tight tracking-wider pb-2 sm:text-lg md:text-lg lg:text-xl">
                <p>Hello, Folks</p>
                <p>Wanna know your manager and division? Remember the letter!</p>
            </div>
            <div class="flex flex-col items-center">
                <img src="/static/logo_imac.png" class="h-6 mr-3 sm:h-12" alt="IMAC Logo" />
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSe3_7ZODnsvBSg5o19hzqTokj1iYyuLWWCSX5GQIZJGTxpQvA/viewform" class="inline-flex items-center px-4 py-2.5 mt-4 text-xs md:text-sm font-medium text-center text-white bg-red-600 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
                    Welcome Party RSVP
                </a>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock content %}

IMAC/mainweb/templates/rejected.html
{% extends "base_generic.html" %}

{% block content %}
<div class="flex flex-col items-center">
    <div class=" flex max-h-screen">
    <div class="flex flex-col self-center items-center py-4 px-6 m-10 items-center bg-transparent backdrop-blur rounded-3xl xl:mx-48" >
        <div>    
            <h1 class="text-[#dad2c9] text-5xl text-center font-bold leading-none underline underline-offset-8 decoration-3 lg:decoration-2 decoration-orange-600 sm:text-6xl md:text-7xl lg:text-8xl drop-shadow-[0_5px_5px_rgba(0,0,0,5)]">Thank You</h1>
            <div class="text-lg text-center font-semibold text-white leading-tight tracking-wider py-2 sm:text-lg md:text-lg lg:text-xl">
                <p>very much for your application.</p>
                <p>After very careful consideration,</p>
            </div>
            <div class="mx-[20px] px-2 pb-1 w-auto items-center text-xl text-center font-bold bg-[#dad2c9] text-orange-600 rounded-2xl sm:text-xl md:text-xl lg:text-2xl" > 
                <p>We regret to inform you that your</p>
                <p>application has not been selected</p>
            </div>
            <div class="text-lg text-center font-semibold text-white pt-4 leading-tight tracking-wider sm:text-lg md:text-lg lg:text-xl">
                <p>Thank you for the interest you have</p>
                <p>shown and wish you every success</p>
                <p>in finding another new opportunity!</p>
                <a href="{% url 'home' %}" class="inline-flex items-center px-4 py-2.5 mt-4 text-xs md:text-sm font-medium text-center text-white bg-red-600 rounded-lg hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
                    Home
                </a>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock content %}

IMAC/mainweb/templates/uploadlolos.html
{% extends 'base_generic.html' %}
{% block content %}
<h4>Import CSV File</h4>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="newstaff_file">
    <button type="submit">Upload</button>
  </form>
{% endblock %}